### ISSUE TITLE
[Bug?] The specified checksum type is not supported by Vagrant: SHA256

### ISSUE THREAD

**Issue by bsdooby** [gusztavvargadr/vagrant#95]
When I try to `vagrant up` from https://vagrantcloud.com/api/v2/vagrant/gusztavvargadr/visual-studio-2019-community-windows-10. I get the above error.

This issue occurs on a Linux Slackware64 "-current", using Vagrant 2.4.1 and VirtualBox 7.0.19r163060. A few days ago, I installed a similiar setup (also from your repos), and the error did not occur (IIRC).

**Comment by gusztavvargadr** [comment]
Hi @bsdooby, I have never seen this error before.

Can you maybe try following the official instructions of running with debugging enabled and share the logs and your Vagrant file and configuration? Then I can try to take a look.

https://developer.hashicorp.com/vagrant/docs/other/debugging

**Comment by bsdooby** [comment]
Will do. Thank you for your init. feedback.

**Comment by bsdooby** [comment]
```
...
INFO interface: detail: Progress: 99% (Rate: 20.6M/s, Estimated time remaining: --:--:--)
Progress: 99% (Rate: 20.6M/s, Estimated time remaining: --:--:--)DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31663
DEBUG subprocess: Exit status: 0

 INFO interface: detail: Calculating and comparing box checksum...
 INFO interface: detail:     default: Calculating and comparing box checksum...
    default: Calculating and comparing box checksum...
 INFO box_add: Validating checksum with SHA256
 INFO box_add: Expected checksum: 665803c04bdbd54a4e6596ce815214a999a4842e1a6348fca548d3a7e6cfc299
DEBUG box_add: Deleting temporary box: /root/.vagrant.d/tmp/box84bd1fc8908e8a5d3b140c16030a289c392bf8a6
ERROR warden: Error occurred: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007f1b24a47d38>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-91db0b97139bdfb9b5c90d66f5b4ca93
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f1b24ed2ec0>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::BoxChecksumInvalidType: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512>
ERROR vagrant: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/file_checksum.rb:71:in `load_digest'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/file_checksum.rb:36:in `initialize'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:626:in `new'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:626:in `validate_checksum'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:423:in `box_add'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:343:in `add_from_metadata'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/box_add.rb:158:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:87:in `handle_box'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:45:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `synchronize'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/handle_box.rb:39:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builtin/call.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/providers/virtualbox/action/check_virtualbox.rb:23:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:247:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:216:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:649:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/machine.rb:202:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/batch_action.rb:89:in `block (2 levels) in run'
 INFO interface: error: The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:

md5, sha1, sha256, sha384, sha512
 INFO interface: Machine: error-exit ["Vagrant::Errors::BoxChecksumInvalidType", "The specified checksum type is not supported by Vagrant: SHA256.\nVagrant supports the following checksum types:\n\nmd5, sha1, sha256, sha384, sha512"]
```

**Comment by bsdooby** [comment]
`ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]`

**Comment by PaulNacamuli** [comment]
Also seeing this.  I have a new workstation where I built machines on 18 June.
I shared the same vagrantfile with a colleague and he gets this error.
Removing my cached downloads, I get the same error.

config.vm.box = "baunegaard/win11pro-en" I do not see this.

(I note that the checksum is uppercase but the supported are all lower case so I wonder if there's something that has added to a file a different case?)

Vagrant 2.4.1 in all cases.

**Comment by bsdooby** [comment]
Other vagrant distros (e.g. generic/ubuntu or similar) do not seem to have
this issue.
Yes, it seems to be a "casing" issue. Windows-specific build files?

**Comment by gusztavvargadr** [comment]
@bsdooby @PaulNacamuli thanks for the details. This is tracked in more detail at https://github.com/gusztavvargadr/packer/issues/444 if you think.

**Comment by bsdooby** [comment]
Dear Gusztáv ( @gusztavvargadr )
Thx for the update and your work/support.

**Comment by gusztavvargadr** [comment]
@bsdooby the mentioned box (and all my other boxes) should be working again.

I am closing this issue in favor of https://github.com/gusztavvargadr/packer/issues/444, but please let me know if you encounter any additional issues.
